### ISSUE TITLE
Error after restarting the ipykernel 

### ISSUE THREAD

**Issue by RicardoLopezDoria** [deepqmc/deepqmc#214] opened 2024-09-24 23:54 UTC
Hi,
I just made a fresh install of deepqmc. I'm using Conda as an environment management tool. I did:

```
$ conda create --name deepQMCEnv python=3.10
$ conda activate deepQMCEnv
$ mkdir deepqmcNew
$ cd deepqmcNew/
$ git clone https://github.com/deepqmc/deepqmc
$ cd deepqmc/
$ pip install -e .[dev]
```
Everything was working fine. And I didn't get any errors. I was using a jupyter notebook. When I kill the ipykernel and then rerun the code, I suddenly get this error when running:

```
from deepqmc.molecule import Molecule
from deepqmc.hamil import MolecularHamiltonian

mol = Molecule.from_name('He')
H = MolecularHamiltonian(mol=mol)
```
error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 4
      1 from deepqmc.molecule import Molecule
      2 from deepqmc.hamil import MolecularHamiltonian
----> 4 mol = Molecule.from_name('He')
      5 H = MolecularHamiltonian(mol=mol)

File ~/deepQMC/deepqmcNew/deepqmc/src/deepqmc/molecule.py:113, in Molecule.from_name(cls, name)
    105 """Create a molecule from a database of named molecules.
    106 
    107 The available names are in :attr:`Molecule.all_names`.
   (...)
    110     name (str): name of the molecule (one of :attr:`Molecule.all_names`)
    111 """
    112 if name in cls.all_names:
--> 113     mol = deepcopy(read_molecule_dataset(mol_conf_dir(), whitelist=name)[name])
    114 else:
    115     raise ValueError(f'Unknown molecule name: {name}')

File ~/deepQMC/deepqmcNew/deepqmc/src/deepqmc/molecule.py:151, in read_molecule_dataset(dataset, whitelist)
    149         continue
    150     with open(f, 'r') as stream:
--> 151         molecules[filename] = Molecule(**yaml.safe_load(stream))
    152 return molecules

File ~/deepQMC/deepqmcNew/deepqmc/src/deepqmc/molecule.py:75, in Molecule.__init__(self, coords, charges, charge, spin, unit, data)
     71         object.__setattr__(self, k, v)
     73 unit_multiplier = {'bohr': null, 'angstrom': angstrom_to_bohr}[unit]
     74 set_attr(
---> 75     coords=unit_multiplier(jnp.array(coords)),
     76     charges=jnp.array(charges, dtype=float),
     77     charge=charge,
     78     spin=spin,
     79     data=data or {},
     80 )
     82 # Derived properties
     83 set_attr(
     84     n_atom_types=len(jnp.unique(jnp.array(charges))),
     85 )

File ~/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py:4086, in array(object, dtype, copy, order, ndmin, device)
   4084 else:
   4085   raise TypeError(f"Unexpected input type for array: {type(object)}")
-> 4086 out_array: Array = lax_internal._convert_element_type(
   4087     out, dtype, weak_type=weak_type, sharding=sharding)
   4088 if ndmin > ndim(out_array):
   4089   out_array = lax.expand_dims(out_array, range(ndmin - ndim(out_array)))

File ~/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/lax/lax.py:571, in _convert_element_type(operand, new_dtype, weak_type, sharding)
    569   return operand
    570 else:
--> 571   return convert_element_type_p.bind(
    572       operand, new_dtype=new_dtype, weak_type=bool(weak_type),
    573       sharding=sharding)

File ~/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/lax/lax.py:2609, in _convert_element_type_bind(operand, new_dtype, weak_type, sharding)
   2608 def _convert_element_type_bind(operand, *, new_dtype, weak_type, sharding):
-> 2609   operand = core.Primitive.bind(convert_element_type_p, operand,
   2610                                 new_dtype=new_dtype, weak_type=weak_type,
   2611                                 sharding=sharding)
   2612   if sharding is not None:
   2613     operand = pjit.with_sharding_constraint(operand, sharding)

File ~/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/core.py:439, in Primitive.bind(self, *args, **params)
    436 def bind(self, *args, **params):
    437   assert (not config.enable_checks.value or
    438           all(isinstance(arg, Tracer) or valid_jaxtype(arg) for arg in args)), args
--> 439   return self.bind_with_trace(find_top_trace(args), args, params)

File ~/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/core.py:443, in Primitive.bind_with_trace(self, trace, args, params)
    441 def bind_with_trace(self, trace, args, params):
    442   with pop_level(trace.level):
--> 443     out = trace.process_primitive(self, map(trace.full_raise, args), params)
    444   return map(full_lower, out) if self.multiple_results else full_lower(out)

File ~/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/core.py:949, in EvalTrace.process_primitive(self, primitive, tracers, params)
    947   return call_impl_with_key_reuse_checks(primitive, primitive.impl, *tracers, **params)
    948 else:
--> 949   return primitive.impl(*tracers, **params)

File ~/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/dispatch.py:88, in apply_primitive(prim, *args, **params)
     86 prev = lib.jax_jit.swap_thread_local_state_disable_jit(False)
     87 try:
---> 88   outs = fun(*args)
     89 finally:
     90   lib.jax_jit.swap_thread_local_state_disable_jit(prev)

ValueError: std::bad_cast
```
This is my pip freeze:

```
absl-py==2.1.0
antlr4-python3-runtime==4.9.3
anyio @ file:///croot/anyio_1706220167567/work
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///tmp/build/80754af9/argon2-cffi-bindings_1644553347904/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
async-lru @ file:///croot/async-lru_1699554519285/work
attrs @ file:///croot/attrs_1695717823297/work
Babel @ file:///croot/babel_1671781930836/work
beautifulsoup4 @ file:///croot/beautifulsoup4-split_1718029820055/work
black==24.8.0
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
Bottleneck @ file:///croot/bottleneck_1707864210935/work
Brotli @ file:///croot/brotli-split_1714483155106/work
certifi @ file:///croot/certifi_1725551672989/work/certifi
cffi @ file:///croot/cffi_1726856441404/work
cfgv==3.4.0
charset-normalizer @ file:///croot/charset-normalizer_1721748349566/work
chex==0.1.86
click==8.1.7
cloudpickle==3.0.0
codespell==2.3.0
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1725269181790/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
-e git+https://github.com/deepqmc/deepqmc@b29abbfec24412641e26dceaad3f4021bb9fdddd#egg=deepqmc
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
distlib==0.3.8
distrax==0.1.5
dm-haiku==0.0.12
dm-tree==0.1.8
etils==1.9.4
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1720869315914/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1725214404607/work
fastjsonschema @ file:///opt/conda/conda-bld/python-fastjsonschema_1661371079312/work
filelock==3.16.1
flake8==7.1.1
flake8-bugbear==24.8.19
flake8-comprehensions==3.15.0
flake8-quotes==3.4.0
flax==0.9.0
fsspec==2024.9.0
gast==0.6.0
h11 @ file:///croot/h11_1706652277403/work
h5py==3.11.0
httpcore @ file:///croot/httpcore_1706728464539/work
httpx @ file:///croot/httpx_1723474802858/work
humanize==4.10.0
hydra-core==1.3.2
identify==2.6.1
idna @ file:///croot/idna_1714398848350/work
immutabledict==4.2.0
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1726082825846/work
importlib_resources==6.4.5
iniconfig==2.0.0
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1719845459717/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1725050136642/work
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1724334859652/work
isort==5.13.2
jax==0.4.33
jax_dataclasses==1.6.1
jaxlib==0.4.33
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2 @ file:///croot/jinja2_1716993405101/work
jmp==0.0.4
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonschema @ file:///croot/jsonschema_1699041609003/work
jsonschema-specifications @ file:///croot/jsonschema-specifications_1699032386549/work
jupyter-events @ file:///croot/jupyter_events_1718738097486/work
jupyter-lsp @ file:///croot/jupyter-lsp-meta_1699978238815/work
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1726610684920/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1710257277185/work
jupyter_server @ file:///croot/jupyter_server_1718827083372/work
jupyter_server_terminals @ file:///croot/jupyter_server_terminals_1686870725608/work
jupyterlab @ file:///croot/jupyterlab_1725895214311/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab_server @ file:///croot/jupyterlab_server_1725865349919/work
jupyterlab_widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1724331334887/work
kfac-jax==0.0.6
markdown-it-py==3.0.0
MarkupSafe @ file:///croot/markupsafe_1704205993651/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1713250518406/work
mccabe==0.7.0
mdurl==0.1.2
mistune @ file:///opt/conda/conda-bld/mistune_1661496219659/work
ml_dtypes==0.5.0
msgpack==1.1.0
mypy==1.11.2
mypy-extensions==1.0.0
nbclient @ file:///croot/nbclient_1698934205032/work
nbconvert @ file:///croot/nbconvert_1699022732553/work
nbformat @ file:///croot/nbformat_1694616755618/work
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
nodeenv==1.9.1
notebook @ file:///croot/notebook_1725954770513/work
notebook_shim @ file:///croot/notebook-shim_1699455894279/work
numexpr @ file:///croot/numexpr_1696515281613/work
numpy @ file:///croot/numpy_and_numpy_base_1708638617955/work/dist/numpy-1.26.4-cp310-cp310-linux_x86_64.whl#sha256=ce136f308f566617937abac6c8f280bd61b41c12ab7eb7d8784c5795c5be477b
omegaconf==2.3.0
opt-einsum==3.3.0
optax==0.2.3
orbax-checkpoint==0.6.4
overrides @ file:///croot/overrides_1699371140756/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1718189413536/work
pandas @ file:///croot/pandas_1718308974269/work/dist/pandas-2.2.2-cp310-cp310-linux_x86_64.whl#sha256=a2434a313a5eb5b4fdbec6c770abfde859f643eff7b3a703791bf8b73e54c394
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1712320355065/work
pathspec==0.12.1
pep8-naming==0.14.1
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1706113125309/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1726613481435/work
pluggy==1.5.0
pre-commit==3.8.0
prometheus-client @ file:///tmp/abs_d3zeliano1/croots/recipe/prometheus_client_1659455100375/work
prompt_toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1718047967974/work
protobuf==5.28.2
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1725737838492/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure_eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1721585709575/work
pycodestyle==2.12.1
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydocstyle==6.3.0
pyflakes==3.2.0
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
pyright==1.1.381
pyscf==2.6.2
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
pytest==8.3.3
pytest-datadir==1.5.0
pytest-regressions==2.5.0
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
python-json-logger @ file:///croot/python-json-logger_1683823803357/work
pytz @ file:///croot/pytz_1713974312559/work
PyYAML @ file:///croot/pyyaml_1698096049011/work
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1725448950123/work
referencing @ file:///croot/referencing_1699012038513/work
requests @ file:///croot/requests_1721410876868/work
rfc3339-validator @ file:///croot/rfc3339-validator_1683077044675/work
rfc3986-validator @ file:///croot/rfc3986-validator_1683058983515/work
rich==13.8.1
rpds-py @ file:///croot/rpds-py_1698945930462/work
scipy==1.14.1
Send2Trash @ file:///croot/send2trash_1699371139552/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio @ file:///croot/sniffio_1705431295498/work
snowballstemmer==2.2.0
soupsieve @ file:///croot/soupsieve_1696347547217/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
tabulate==0.9.0
tensorboardX==2.6.2.2
tensorflow-probability==0.24.0
tensorstore==0.1.65
terminado @ file:///croot/terminado_1671751832461/work
tinycss2 @ file:///croot/tinycss2_1668168815555/work
tomli @ file:///opt/conda/conda-bld/tomli_1657175507142/work
toolz==0.12.1
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1724960687225/work
tqdm==4.66.5
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1713535121073/work
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1717802530399/work
tzdata @ file:///croot/python-tzdata_1690578112552/work
uncertainties==3.2.2
urllib3 @ file:///croot/urllib3_1718912636303/work
virtualenv==20.26.5
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
webencodings==0.5.1
websocket-client @ file:///croot/websocket-client_1715878298792/work
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1724331337528/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1726248574750/work
```
I don't have a clue what could be the problem. What I can say is that I wasn't getting any errors until I restarted the ipykernel, then I got the error.

Thanks in advance.

**Comment by zenoone** [comment] 2024-09-27 10:14
Hi Ricardo,

the error you experience seems to be related to your `jax` installation. It occurs on the very first instance an array is initialized. In order to isolate the problem you may want to make a new notebook import `jax.numpy`, instantiate an array and check if the error persists. Likely, the error will also show up if you just open a python console (from your virtual environment), import `jax` and instantiate an array there. This will further strip of a layer of complexity. 

In [this issue](https://github.com/jax-ml/jax/issues/21964) the error was resolved by a fresh install of the environment. Ofc, I understand that you don't want to install `deepqmc` every time you restart your kernel, but going through that process again might help to debug. 

I would suggest the following:
- make a new environment and install `deepqmc` just the way you described
- run `deepqmc` from the command line (see [command line interface](https://deepqmc.github.io/cli.html))
- run again, does the error show up?
- If not - revisit your `jupyter` notebook. Firstly just import `jax`, instanciate and array, restart the kernel and do it again, does the error show up?
- If not - run the original notebook cell by cell, as in first all cells up to 1, restart all cells up to 2, etc.

Make sure that you only install `deepqmc` and its dependencies (and `jupyter` as soon as you want to run the notebook).

Let me know if you can further locate the origin of the error. Unfortunately, it is not possible for me to reproduce this error in my setup and give more concrete instructions.

**Comment by RicardoLopezDoria** [comment] 2024-10-02 21:13
As you pointed out, with the previous environment just creating a jax array shows an error:
```
>>> import jax.numpy as jnp
>>> jnp.array(42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ricardol/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4086, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/ricardol/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 571, in _convert_element_type
    return convert_element_type_p.bind(
  File "/home/ricardol/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 2609, in _convert_element_type_bind
    operand = core.Primitive.bind(convert_element_type_p, operand,
  File "/home/ricardol/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/core.py", line 439, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/ricardol/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/core.py", line 443, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/ricardol/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/core.py", line 949, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/ricardol/anaconda3/envs/deepQMCEnv/lib/python3.10/site-packages/jax/_src/dispatch.py", line 88, in apply_primitive
    outs = fun(*args)
ValueError: std::bad_cast
``` 
Then I did as you suggested:

- make a new environment and install deepqmc just the way you described
Done
- run deepqmc from the command line (see [command line interface](https://deepqmc.github.io/cli.html))
Done
- run again, does the error show up?
Done, not showing any errors.

- If not - revisit your jupyter notebook. Firstly just import jax, instanciate and array, restart the kernel and do it again, does the error show up?

I ran:
``` 
import jax.numpy as jnp
jnp.array(42)
```
I restarted the kernel and reran it; I got no errors.

- If not - run the original notebook cell by cell, as in first all cells up to 1, restart all cells up to 2, etc.
Weirdly, this didn't create any errors either (so far). 

I think maybe something weird happened in the previous environment that created the error with Jax when I restarted the ipykernel. 

Thanks a lot.

**Comment by zenoone** [comment] 2024-10-04 08:50
Glad to hear everything is working as intended. I'm closing this issue as solved.

**Closed by zenoone** 2024-10-04 08:50 UTC
