### ISSUE TITLE
Encounter an error when running the tutorial

### ISSUE THREAD

**Issue by jongharyu** [deepqmc/deepqmc#162] opened 2023-08-24 18:20 UTC
On the most recent `master` (`bf297a34c0304f9deb3a5ad704ddd3a8a3d7eea0`), when I run the tutorial example, I encountered `TypeError: __init__() got an unexpected keyword argument 'w_init'` at
the line `train(H, ansatz, 'kfac', sampler, steps=10000, sample_size=2000, seed=42)`.
I checked that there is no error with the past commit `b7b8789de85215b4bf94f062e3087a892d1f11f2`.
Attached is the full traceback. 

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [17], in <cell line: 1>()
----> 1 train(H, ansatz, 'kfac', sampler, steps=10000, sample_size=2000, seed=42)

File ~/src/quantum/deepqmc/src/deepqmc/train.py:173, in train(hamil, ansatz, opt, sampler, steps, sample_size, seed, mols, workdir, train_state, init_step, max_restarts, max_eq_steps, pretrain_steps, pretrain_kwargs, opt_kwargs, fit_kwargs, chkptdir, chkpts_kwargs, metric_logger, mol_idx_factory)
    171 else:
    172     rng, rng_init = jax.random.split(rng, 2)
--> 173     params = init_wf_params(rng_init, hamil, ansatz)
    174     num_params = tree_util.tree_reduce(
    175         operator.add, tree_util.tree_map(lambda x: x.size, params)
    176     )
    177     log.info(f'Number of model parameters: {num_params}')

File ~/src/quantum/deepqmc/src/deepqmc/wf/base.py:17, in init_wf_params(rng, hamil, ansatz)
     15     R_shape = 0
     16 phys_conf = hamil.init_sample(rng_sample, jnp.zeros(R_shape), 1)[0]
---> 17 params = ansatz.init(rng_params, phys_conf)
     18 return params

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/transform.py:170, in without_state.<locals>.init_fn(*args, **kwargs)
    169 def init_fn(*args, **kwargs) -> hk.MutableParams:
--> 170   params, state = f.init(*args, **kwargs)
    171   if state:
    172     raise base.NonEmptyStateError(
    173         "If your transformed function uses `hk.{get,set}_state` then use "
    174         "`hk.transform_with_state`.")

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/transform.py:427, in transform_with_state.<locals>.init_fn(rng, *args, **kwargs)
    425 with base.new_context(rng=rng) as ctx:
    426   try:
--> 427     f(*args, **kwargs)
    428   except jax.errors.UnexpectedTracerError as e:
    429     raise jax.errors.UnexpectedTracerError(unexpected_tracer_hint) from e

Input In [14], in ansatz(phys_conf, return_mos)
     18 @hk.without_apply_rng
     19 @hk.transform
     20 def ansatz(phys_conf, return_mos=False):
---> 21     return _ansatz(H)(phys_conf, return_mos=return_mos)

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/module.py:146, in ModuleMetaclass.__call__(cls, *args, **kwargs)
    144 # Now attempt to initialize the object.
    145 init = wrap_method("__init__", cls.__init__, lambda: cls)
--> 146 init(module, *args, **kwargs)
    148 if (config.get_config().module_auto_repr and
    149     getattr(module, "AUTO_REPR", True)):
    150   module._auto_repr = utils.auto_repr(cls, *args, **kwargs)  # pylint: disable=protected-access

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/module.py:465, in wrap_method.<locals>.wrapped(self, *args, **kwargs)
    462   if method_name != "__call__":
    463     f = jax.named_call(f, name=method_name)
--> 465 out = f(*args, **kwargs)
    467 # Module names are set in the constructor. If `f` is the constructor then
    468 # its name will only be set **after** `f` has run. For methods other
    469 # than `__init__` we need the name before running in order to wrap their
    470 # execution with `named_call`.
    471 if module_name is None:

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/module.py:306, in run_interceptors(bound_method, method_name, self, orig_class, *args, **kwargs)
    304 """Runs any method interceptors or the original method."""
    305 if not interceptor_stack:
--> 306   return bound_method(*args, **kwargs)
    308 ctx = MethodContext(module=self,
    309                     method_name=method_name,
    310                     orig_method=bound_method,
    311                     orig_class=orig_class)
    312 interceptor_stack_copy = interceptor_stack.clone()

File ~/src/quantum/deepqmc/src/deepqmc/wf/nn_wave_function/nn_wave_function.py:92, in NeuralNetworkWaveFunction.__init__(self, hamil, omni_factory, envelope, backflow_op, n_determinants, full_determinant, cusp_electrons, cusp_alpha, backflow_transform, conf_coeff)
     90 self.n_det = n_determinants
     91 self.full_determinant = full_determinant
---> 92 self.envelope = envelope(hamil.mol, n_determinants)
     93 self.conf_coeff = conf_coeff(1, name='conf_coeff')
     94 self.cusp_same, self.cusp_anti = (
     95     (ElectronicAsymptotic(cusp=cusp, alpha=cusp_alpha) for cusp in (0.25, 0.5))
     96     if cusp_electrons
     97     else (None, None)
     98 )

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/module.py:146, in ModuleMetaclass.__call__(cls, *args, **kwargs)
    144 # Now attempt to initialize the object.
    145 init = wrap_method("__init__", cls.__init__, lambda: cls)
--> 146 init(module, *args, **kwargs)
    148 if (config.get_config().module_auto_repr and
    149     getattr(module, "AUTO_REPR", True)):
    150   module._auto_repr = utils.auto_repr(cls, *args, **kwargs)  # pylint: disable=protected-access

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/module.py:465, in wrap_method.<locals>.wrapped(self, *args, **kwargs)
    462   if method_name != "__call__":
    463     f = jax.named_call(f, name=method_name)
--> 465 out = f(*args, **kwargs)
    467 # Module names are set in the constructor. If `f` is the constructor then
    468 # its name will only be set **after** `f` has run. For methods other
    469 # than `__init__` we need the name before running in order to wrap their
    470 # execution with `named_call`.
    471 if module_name is None:

File ~/opt/anaconda3/envs/quantum/lib/python3.9/site-packages/haiku/_src/module.py:306, in run_interceptors(bound_method, method_name, self, orig_class, *args, **kwargs)
    304 """Runs any method interceptors or the original method."""
    305 if not interceptor_stack:
--> 306   return bound_method(*args, **kwargs)
    308 ctx = MethodContext(module=self,
    309                     method_name=method_name,
    310                     orig_method=bound_method,
    311                     orig_class=orig_class)
    312 interceptor_stack_copy = interceptor_stack.clone()

TypeError: __init__() got an unexpected keyword argument 'init_to_ones'
```

**Comment by szbernat** [comment] 2023-08-28 17:48
Hi,

Thanks for reporting this, I'll push a fix ASAP!

Thanks for trying DeepQMC!

**Comment by szbernat** [comment] 2023-08-29 13:52
Hi,
Unfortunately, I couldn't reproduce the error on commit `bf297a34`. Could you try running this script (which is a concatenation of the tutorial commands), to see if it works?
```python
import os

import haiku as hk
from hydra import compose, initialize_config_dir
from hydra.utils import instantiate

import deepqmc
from deepqmc import MolecularHamiltonian, Molecule, train
from deepqmc.sampling import DecorrSampler, MetropolisSampler, chain

mol = Molecule.from_name('LiH')

H = MolecularHamiltonian(mol=mol)

deepqmc_dir = os.path.dirname(deepqmc.__file__)
config_dir = os.path.join(deepqmc_dir, 'conf/ansatz')

with initialize_config_dir(version_base=None, config_dir=config_dir):
    cfg = compose(config_name='default')

_ansatz = instantiate(cfg, _recursive_=True)


@hk.without_apply_rng
@hk.transform
def ansatz(phys_conf, return_mos=False):
    return _ansatz(H)(phys_conf, return_mos=return_mos)


sampler = chain(DecorrSampler(length=20), MetropolisSampler(H))

train(H, ansatz, 'kfac', sampler, steps=10000, sample_size=100, seed=42)
```

**Comment by jongharyu** [comment] 2023-08-29 14:34
Thanks for looking into this! I just tried the snippet again and it seems to work. 
I think I was somehow running the codebase on a wrong conda environment. Sorry for the hassle.

**Comment by szbernat** [comment] 2023-08-29 14:35
No problem, glad it's working!

**Comment by Digoba** [comment] 2023-08-31 17:55
Hello! 
I'm having the same problem running the tutorial with PauliNet as ansatz.
<img width="1072" alt="image" src="https://github.com/deepqmc/deepqmc/assets/106712012/a1c82b73-d9f8-4d6f-a759-b416a1f6ff4f">

This is the code:

<img width="807" alt="image" src="https://github.com/deepqmc/deepqmc/assets/106712012/d620bc28-31ed-458e-aee3-0508d130a071">

**Comment by szbernat** [comment] 2023-09-01 09:14
Hi Digoba,

Thank you for reporting this!

There is indeed a small error in the configuration file for the `PauliNet` ansatz. A [PR](https://github.com/deepqmc/deepqmc/pull/165) with a fix has been created. Let us know if you run into any other issues.

Thanks for trying `deepqmc`.

**Comment by Digoba** [comment] 2023-09-01 19:15
Thank you so mucho for your response. I have no problem running the code using what you told me. 
I'm having another issue while working with deeperwin. 
The training crashes with less than 100 steps. 
Do you know what should happened?
I attach a screenshot of the error:

**Closed** 2023-09-19 09:55 UTC
